apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wxr3c5vuy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wxr3c5vuy-go 
  name: wxr3c5vuy-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wxr3c5vuy-go 
